[package]
name = "ferx"
description = "Cause it's ferxing time!!!"
version = "0.1.0"
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.22.2"
x11 = "2.18.2"
regex = "1.5"
libc = "0.2.101"